### ISSUE TITLE
Checklist burocrática

### ISSUE THREAD

**Issue by joaoandrepestre** [joaoandrepestre/tcc-glitch-art#1]
- [x] 1. Achar orientador + tema de projeto
- [x] 2. Mandar pro Flávio com um roadmap a Proposta de Projeto
- [x] 3. Escrever o projeto
- [x] 4. Validar o projeto escrito com o seu orientador (esse é um for loop com o de cima)
- [x] 5. Preparar a Banca e marcar a data da defesa
- [x] 6. Validar a banca com o Flávio
- [x] 7. Defender
- [x] 8. (Seu orientador na teoria, na prática você) - Assinar a folha de atas com todas as assinaturas da banca + a nota
- [x] 9. Providenciar as correções da banca
- [x] 10. Validar as correções com o orientador
- [x] 11. Mandar dnv pra banca assinar a contracapa com o documento definitivo + assinar você um termo de ética
- [x] 12. Mandar pro Flávio pra ele validar também
- [x] 12.1. (Opcional) Fazer correções documentais caso o Flávio peça
- [x] 13. Receber o Nada Consta do Flávio e mandar pra Secretaria
- [ ] 14. Receber o RCS (a folha de lançamento de nota) da secretaria e mandar DE NOVO pro Flávio e o Luidi assinarem
- [ ] 15. Mandar a RCS assinada pra secretaria

**Comment by jg-lopes** [comment]
Acrescentar créditos ao autor
